[technote]
id = "RTN-048"
series_id = "RTN"
canonical_url = "https://rtn-048.lsst.io/"
github_url = "https://github.com/lsst/rtn-048"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Eric H.", family = "Neilsen, Jr."}
internal_id = "neilsene"
orcid = "https://orcid.org/0000-0002-7357-0317"
[[technote.authors.affiliations]]
name = "Fermi National Accelerator Laboratory"
internal_id = "Fermilab"
address = "P. O. Box 500, Batavia, IL 60510, USA"

[[technote.authors]]
name = {given = "R. Lynne", family = "Jones"}
internal_id = "jonesrl"
orcid = "https://orcid.org/0000-0001-5916-0031"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"

[[technote.authors]]
name = {given = "Peter", family = "Yoachim"}
internal_id = "yoachimp"
orcid = "https://orcid.org/0000-0003-2874-6464"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
